#$L$
# Copyright (C) 2015 Ridgerun (http://www.ridgerun.com). 
##$L$

FETCHER_NO_DOWNLOAD=yes

BINARIES = /usr/bin/Tutorial

include ../../bsp/classes/rrsdk.defs
include ../../bsp/classes/cmake.class

