#$L$
# Copyright (C) 2014 Ridgerun (http://www.ridgerun.com). 
#$L$

PKG_URL=https://pypi.python.org/packages/source/p/pexpect
PKG_TARBALL=pexpect-3.2.tar.gz
PKG_SHA1SUM=5eb7882f5baa194c0cae9bdfc24c8adc22caa783
FETCHER_EXTRACT_DIRECTORY_NAME=src

include ../../../bsp/classes/rrsdk_local.class
include $(CLASSES)/python_local.class

