#$L$
# Copyright (C) 2014 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=https://pypi.python.org/packages/source/w/watchdog
PKG_TARBALL=watchdog-0.8.1.tar.gz
PKG_SHA1SUM=16ebdd3b456b5ddfb82cf87da55d33f4497bb5ed
FETCHER_EXTRACT_DIRECTORY_NAME=src

PYTHON_PKG_FILES_DIR=src/src/

PYTHON_PKG=watchdog
PYTHON_PKG_FILES=$(PYTHON_PKG)/{*.py,observers/*.py,tricks/*,utils/*}

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/python.class
