#$L$
# Copyright (C) 2014 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=https://pypi.python.org/packages/source/p/pathtools
PKG_TARBALL=pathtools-0.1.2.tar.gz
PKG_SHA1SUM=765b6a002a23d802d6a02d5c1bd14922339c98c1
FETCHER_EXTRACT_DIRECTORY_NAME=src

PYTHON_PKG=pathtools
PYTHON_PKG_FILES=$(PYTHON_PKG)/*.py

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/python.class
