#$L$
# Copyright (C) 2013 Ridgerun (http://www.ridgerun.com). 
#$L$

FETCHER_EXTRACT_DIRECTORY_NAME=src
PKG_URL=https://pypi.python.org/packages/source/t/termcolor
PKG_TARBALL=termcolor-1.1.0.tar.gz
PKG_SHA1SUM=52045880a05c0fbd192343d9c9aad46a73d20e8c

include ../../../bsp/classes/rrsdk_local.class
include $(CLASSES)/python_local.class
