#$L$
# Copyright (C) 2015 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://downloads.sourceforge.net/project/giflib/giflib-5.x
PKG_TARBALL=giflib-5.0.0.tar.bz2
PKG_SHA1SUM=0b032c2104a0956e2f91b6c11ff8c5515421cd8b

#AUTOTOOLS_PARAMS=

BINARIES= /usr/bin/{gif2raw,gif2rgb,gifbuild,gifecho,giffix,gifinter,gifinto,giftext,giftool,gifclrmp}
LIBRARIES= /usr/lib/libgif.so.6.0.0
LINKS= /usr/lib/{libgif.so,libgif.so.6}

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class

