#$L$
# Copyright (C) 2013 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://www.rcdrummond.net/fbdump/
PKG_TARBALL=fbdump-0.4.2.tar.gz
PKG_SHA1SUM=cdc0a0e3cf3ae4e0d618772cfddde7051545a970

BINARIES= /usr/bin/fbdump
FETCHER_EXTRACT_DIRECTORY_NAME=src
AUTOTOOLS_PARAMS= ac_cv_func_malloc_0_nonnull=yes

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class
