#$L$
# Copyright (C) 2011 Ridgerun (http://www.ridgerun.com). 
#$L$

include ../../../bsp/classes/rrsdk_local.class
include $(CLASSES)/autotools_local.class

PKG_URL=http://ftp.gnu.org/pub/gnu/gettext/
PKG_TARBALL=gettext-0.18.1.1.tar.gz
PKG_SHA1SUM=5009deb02f67fc3c59c8ce6b82408d1d35d4e38f

AUTOTOOLS_PARAMS=--with-included-libxml --prefix=$(LOCALDIR)
