#$L$
# Copyright (C) 2016 Ridgerun (http://www.ridgerun.com). 
#$L$

PKG_URL=https://pypi.python.org/packages/fa/dd/e310aaaf1702516e12451d2d5eb78175587edc7fbeb1afd58263171e9384
PKG_TARBALL=setuptools-28.2.0.tar.gz
PKG_SHA1SUM=fd9a24b420581116634466b2de8de280131c8ed3
FETCHER_EXTRACT_DIRECTORY_NAME=src

include ../../../bsp/classes/rrsdk_local.class
include $(CLASSES)/python_local.class

