#$L$
# Copyright (C) 2011-2014 Ridgerun (http://www.ridgerun.com)
##$L$

PKG_URL=git://github.com/RidgeRun/gst-openmax-dm81xx.git
PKG_TYPE=git
PKG_REVISION=c49334758ed7d30055caf020bf488f3addf4a1bc

AUTOTOOLS_SRC_DIR=src
# Prevents autogen from running configure
export NOCONFIGURE=yes

include ../../bsp/classes/rrsdk.class
include $(CLASSES)/gstreamer-plugin.class
