#$L$
# Copyright (C) 2015 Ridgerun (http://www.ridgerun.com). 
#$L$

PKG_URL=http://www.nano-editor.org/dist/v2.4/
PKG_TARBALL=nano-2.4.2.tar.gz
PKG_SHA1SUM=bcf2bb3fcc04874cb38c52cfd8feebce61dd5e0a

AUTOTOOLS_PARAMS=CFLAGS="$(CFLAGS)"

BINARIES = /usr/bin/nano

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class
