#$L$
# Copyright (C) 2014 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://prdownloads.sourceforge.net/e2fsprogs
PKG_TARBALL=e2fsprogs-1.42.9.tar.gz
PKG_SHA1SUM=fb8e3662302bcab1682d567d6ee0ff051faa1bbd

BINARIES=/usr/sbin/e2fsck

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class

