#$L$
# Copyright (C) 2016 Ridgerun (http://www.ridgerun.com)
##$L$

PKG_URL = https://xcb.freedesktop.org/dist/
PKG_TARBALL = libpthread-stubs-0.3.tar.gz
PKG_SHA1SUM = 7174d6a5f4b158746f020b8fc7a3e3e5438dd233

DESTDIR=$(FSDEVROOT)
AUTOTOOLS_PARAMS=--prefix=/usr

include ../../../bsp/classes/rrsdk.class
include $(DEVDIR)/bsp/classes/autotools.class
