#$L$
# Copyright (C) 2014 Ridgerun (http://www.ridgerun.com).
#$L$

FETCHER_EXTRACT_DIRECTORY_NAME=src
PKG_URL=https://github.com/RidgeRun/openfd.git
PKG_TYPE=git
PKG_BRANCH=master

include ../../../bsp/classes/rrsdk_local.class
include $(CLASSES)/python_local.class
