#$L$
# Copyright (C) 2011 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://packages.ridgerun.com
PKG_NAME=socketcan-1232
PKG_SHA1SUM=9df0e09d21e5178afe1654f02891468400021020

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class

BINARIES=   /usr/bin/asc2log \
	    /usr/bin/bcmserver \
	    /usr/bin/canbusload \
	    /usr/bin/candump \
	    /usr/bin/canfdtest \
	    /usr/bin/cangen \
	    /usr/bin/canlogserver \
	    /usr/bin/canplayer \
	    /usr/bin/cansend \
	    /usr/bin/cansniffer \
	    /usr/bin/log2asc \
	    /usr/bin/log2long \
	    /usr/bin/slcan_attach \
	    /usr/bin/slcand \
	    /usr/bin/slcanpty
