#$L$
# Copyright (C) 2011-2017 Ridgerun (http://www.ridgerun.com)
##$L$

PKG_URL=https://github.com/RidgeRun/gst-rr-openmax-dm81xx.git
PKG_TYPE=git

PKG_REVISION=6f7c0cc6b3e2f98b4e1e4f6614432b7ef617cfae

AUTOTOOLS_SRC_DIR=src
# Prevents autogen from running configure
export NOCONFIGURE=yes

include ../../bsp/classes/rrsdk.class
include $(CLASSES)/gstreamer-plugin.class
