#$L$
# Copyright (C) 2011 Ridgerun (http://www.ridgerun.com). 
#$L$

include ../../../bsp/classes/rrsdk_local.class
include $(CLASSES)/autotools_local.class

PKG_URL=http://ftp.gnu.org/gnu/automake/
PKG_TARBALL=automake-1.15.tar.gz
PKG_SHA1SUM=b5a840c7ec4321e78fdc9472e476263fa6614ca1
