#$L$
# Copyright (C) 2011 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://people.seas.harvard.edu/~apw/stress/
PKG_TARBALL=stress-1.0.4.tar.gz
PKG_SHA1SUM=e1533bc704928ba6e26a362452e6db8fd58b1f0b

AUTOTOOLS_PARAMS=--prefix=/usr

DESTDIR=$(FSDEVROOT)
BINARIES= /usr/bin/stress

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class

