#!/bin/sh -e

case "$1" in
start)
	echo "Starting D-Bus message bus system"
	mkdir -p /var/run/dbus
	dbus-daemon --system;
	if [ ! -e /etc/machine-id ]; then
		dbus-uuidgen > /etc/machine-id
	fi
	;;

stop)
	echo "Stoping D-Bus message bus system"
	kill -TERM `cat /var/run/dbus/pid` >/dev/null 2>/dev/null;
	rm -f /var/run/dbus/pid
	;;

*)
	echo "Usage: /etc/init.d/dbus {start|stop}"
	exit 1
	;;
esac

exit 0

